services:
  marzneshin:
    image: dawsh/marzneshin:latest
    restart: always
    env_file: .env
    network_mode: host
    environment:
      SQLALCHEMY_DATABASE_URL: "sqlite:////var/lib/marzneshin/db.sqlite3"
    volumes:
      - /var/lib/marzneshin:/var/lib/marzneshin

  marznode:
    image: dawsh/marznode:latest
    restart: always
    network_mode: host
    environment:
      SERVICE_ADDRESS: "127.0.0.1"
      INSECURE: "True"
      XRAY_EXECUTABLE_PATH: "/usr/local/bin/xray"
      XRAY_ASSETS_PATH: "/usr/local/lib/xray"
      XRAY_CONFIG_PATH: "/var/lib/marznode/xray_config.json"
      SSL_KEY_FILE: "/etc/opt/marzneshin/certs/privkey.pem"
      SSL_CERT_FILE: "/etc/opt/marzneshin/certs/fullchain.pem"
    volumes:
      - /var/lib/marznode:/var/lib/marznode
      - /etc/opt/marzneshin/certs:/etc/opt/marzneshin/certs:ro

  nginx:
    image: nginx:latest
    restart: always
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/lib/marzneshin:/var/lib/marzneshin:ro
      - /var/lib/marznode:/var/lib/marznode:ro
      - /etc/opt/marzneshin/certs:/etc/nginx/certs:ro
      - /var/www/html:/var/www/html:ro
