services:
  pasarguard:
    image: pasarguard/panel:v1.0.0-rc-1
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/pasarguard:/var/lib/pasarguard

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - /opt/pasarguard/nginx.conf:/etc/nginx/nginx.conf
      - /var/lib/pasarguard:/etc/nginx/certs
    network_mode: host
    ports:
      - "443:443"
    depends_on:
      - pasarguard
